language: node_js
services:
  - docker
node_js:
  - "stable"
before_install:
  - sudo apt-get install -y imagemagick libmagick++-dev node-gyp curl
  - sudo curl -sL https://deb.nodesource.com/setup_9.x | bash -
  - sudo apt-get install -y nodejs
  - export PATH=$PATH:/opt/ImageMagick/bin
  - npm install

script:
  - npm run test
